GET http://localhost:3001/api/persons/1

###

GET http://localhost:3001/api/persons/99

// Heroku

###

GET https://tranquil-escarpment-87631.herokuapp.com/api/persons/1

###

GET https://tranquil-escarpment-87631.herokuapp.com/api/persons/99